# Generated by Django 3.2.5 on 2021-11-22 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productsmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
    ]
